### ISSUE TITLE
The plugin does not have a valid header

### ISSUE THREAD

**Issue by teguh-santoso** [staticallyio/statically-wp#1]
Plugin showing error "The plugin does not have a valid header" when i click activate.
I think the problem is /wp-content/statically/statically folder. I solve the problem by renaming that folder.

WordPress version : 5.3.2

**Comment by fransallen** [comment]
Hi @teguh-santoso,

Thanks for reporting.

I believe this issue has been fixed in the latest version of the plugin, please update it on your side and see if that resolves the issue.

Best,
Frans
